//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradePlatform.Bcl.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hollard.Bcl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section &apos;{0}&apos; not found..
        /// </summary>
        internal static string ConfigurationErrorSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigurationErrorSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration section &apos;{0}&apos; type mismatch..
        /// </summary>
        internal static string ConfigurationErrorSectionTypeMismatch {
            get {
                return ResourceManager.GetString("ConfigurationErrorSectionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows identity security identifier (SID) is not valid..
        /// </summary>
        internal static string SecurityTokenErrorInvalid {
            get {
                return ResourceManager.GetString("SecurityTokenErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows identity has not been authenticated..
        /// </summary>
        internal static string SecurityTokenErrorNotAuthenticated {
            get {
                return ResourceManager.GetString("SecurityTokenErrorNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No identities found..
        /// </summary>
        internal static string SecurityTokenErrorNotFound {
            get {
                return ResourceManager.GetString("SecurityTokenErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Windows identities supported..
        /// </summary>
        internal static string SecurityTokenErrorNotSupported {
            get {
                return ResourceManager.GetString("SecurityTokenErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        internal static string ServiceControlManagerMessageExit {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services started successfully after {0} seconds..
        /// </summary>
        internal static string ServiceControlManagerMessageStarted {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting services....
        /// </summary>
        internal static string ServiceControlManagerMessageStarting {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to stop services....
        /// </summary>
        internal static string ServiceControlManagerMessageStop {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services stopped successfully after {0} seconds..
        /// </summary>
        internal static string ServiceControlManagerMessageStopped {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping services....
        /// </summary>
        internal static string ServiceControlManagerMessageStopping {
            get {
                return ResourceManager.GetString("ServiceControlManagerMessageStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service started successfully..
        /// </summary>
        internal static string ServiceMessageStarted {
            get {
                return ResourceManager.GetString("ServiceMessageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service....
        /// </summary>
        internal static string ServiceMessageStarting {
            get {
                return ResourceManager.GetString("ServiceMessageStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service stopped successfully..
        /// </summary>
        internal static string ServiceMessageStopped {
            get {
                return ResourceManager.GetString("ServiceMessageStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service....
        /// </summary>
        internal static string ServiceMessageStopping {
            get {
                return ResourceManager.GetString("ServiceMessageStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled service application exception occurred.  The service process will be terminated..
        /// </summary>
        internal static string UnhandledServiceApplicationExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledServiceApplicationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled service thread exception occurred..
        /// </summary>
        internal static string UnhandledServiceThreadExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledServiceThreadExceptionMessage", resourceCulture);
            }
        }
    }
}
